/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutricionistag23.vistas;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author jonac
 */
public class MainMenu extends javax.swing.JFrame {

    private boolean clickVistaPacientes, clickVistaComida, clickVistaDieta, clickVistaInformes;
    private static MainMenu main;

    /**
     * Creates new form MainMenu
     */
    private MainMenu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jlFondo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpPaciente = new javax.swing.JPanel();
        jLPaciente = new javax.swing.JLabel();
        jpComida = new javax.swing.JPanel();
        jLComida = new javax.swing.JLabel();
        jpDieta = new javax.swing.JPanel();
        jLDieta = new javax.swing.JLabel();
        jpInformes = new javax.swing.JPanel();
        jLInformes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Dietas Nutricionista");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/nutricionistag23/vistas/icons/logo1.png")));
        setName("mainMenu"); // NOI18N
        setResizable(false);

        jdpEscritorio.setPreferredSize(new java.awt.Dimension(800, 523));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nutricionistag23/vistas/icons/Fondo 3.png"))); // NOI18N
        jlFondo.setPreferredSize(new java.awt.Dimension(800, 600));

        jdpEscritorio.setLayer(jlFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpEscritorioLayout.createSequentialGroup()
                .addComponent(jlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                .addContainerGap())
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(132, 193, 116));
        jPanel1.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 600));

        jpPaciente.setBackground(new java.awt.Color(195, 255, 184));
        jpPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpPacienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpPacienteMouseExited(evt);
            }
        });

        jLPaciente.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLPaciente.setForeground(new java.awt.Color(0, 54, 3));
        jLPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPaciente.setText("Paciente");

        javax.swing.GroupLayout jpPacienteLayout = new javax.swing.GroupLayout(jpPaciente);
        jpPaciente.setLayout(jpPacienteLayout);
        jpPacienteLayout.setHorizontalGroup(
            jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPacienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPacienteLayout.setVerticalGroup(
            jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jpComida.setBackground(new java.awt.Color(195, 255, 184));
        jpComida.setPreferredSize(new java.awt.Dimension(193, 53));
        jpComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpComidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpComidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpComidaMouseExited(evt);
            }
        });

        jLComida.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLComida.setForeground(new java.awt.Color(0, 54, 3));
        jLComida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLComida.setText("Comida");
        jLComida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLComida.setMaximumSize(new java.awt.Dimension(76, 22));
        jLComida.setMinimumSize(new java.awt.Dimension(76, 22));
        jLComida.setName(""); // NOI18N
        jLComida.setPreferredSize(new java.awt.Dimension(76, 22));

        javax.swing.GroupLayout jpComidaLayout = new javax.swing.GroupLayout(jpComida);
        jpComida.setLayout(jpComidaLayout);
        jpComidaLayout.setHorizontalGroup(
            jpComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpComidaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLComida, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jpComidaLayout.setVerticalGroup(
            jpComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLComida, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jpDieta.setBackground(new java.awt.Color(195, 255, 184));
        jpDieta.setPreferredSize(new java.awt.Dimension(193, 53));
        jpDieta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpDietaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpDietaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpDietaMouseExited(evt);
            }
        });

        jLDieta.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLDieta.setForeground(new java.awt.Color(0, 54, 3));
        jLDieta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDieta.setText("Dieta");
        jLDieta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLDieta.setMaximumSize(new java.awt.Dimension(76, 22));
        jLDieta.setMinimumSize(new java.awt.Dimension(76, 22));
        jLDieta.setName(""); // NOI18N
        jLDieta.setPreferredSize(new java.awt.Dimension(76, 22));

        javax.swing.GroupLayout jpDietaLayout = new javax.swing.GroupLayout(jpDieta);
        jpDieta.setLayout(jpDietaLayout);
        jpDietaLayout.setHorizontalGroup(
            jpDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDietaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpDietaLayout.setVerticalGroup(
            jpDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jpInformes.setBackground(new java.awt.Color(195, 255, 184));
        jpInformes.setPreferredSize(new java.awt.Dimension(193, 53));
        jpInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpInformesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpInformesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpInformesMouseExited(evt);
            }
        });

        jLInformes.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLInformes.setForeground(new java.awt.Color(0, 54, 3));
        jLInformes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLInformes.setText("Informes");
        jLInformes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLInformes.setMaximumSize(new java.awt.Dimension(76, 22));
        jLInformes.setMinimumSize(new java.awt.Dimension(76, 22));
        jLInformes.setName(""); // NOI18N
        jLInformes.setPreferredSize(new java.awt.Dimension(76, 22));

        javax.swing.GroupLayout jpInformesLayout = new javax.swing.GroupLayout(jpInformes);
        jpInformes.setLayout(jpInformesLayout);
        jpInformesLayout.setHorizontalGroup(
            jpInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInformesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpInformesLayout.setVerticalGroup(
            jpInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInformesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nutricionistag23/vistas/icons/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpComida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpDieta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpInformes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jpPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jpComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jpDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jpInformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jdpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpComidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpComidaMouseExited
        if (!clickVistaComida) {
            jpComida.setBackground(new Color(195, 255, 184));
            jLComida.setForeground(new Color(0, 54, 3));
        }
    }//GEN-LAST:event_jpComidaMouseExited

    private void jpComidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpComidaMouseEntered
        jpComida.setBackground(new Color(140, 184, 132));
        jLComida.setForeground(Color.WHITE);
    }//GEN-LAST:event_jpComidaMouseEntered

    private void jpComidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpComidaMouseClicked
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        reinicializarBotones("comida");
        clickVistaComida = true;
        ComidaVista pv = new ComidaVista();
        agregarFondoVentana(pv);
    }//GEN-LAST:event_jpComidaMouseClicked

    private void jpPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPacienteMouseExited
        if (!clickVistaPacientes) {
            jpPaciente.setBackground(new Color(195, 255, 184));
            jLPaciente.setForeground(new Color(0, 54, 3));
        }
    }//GEN-LAST:event_jpPacienteMouseExited

    private void jpPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPacienteMouseEntered
        jpPaciente.setBackground(new Color(140, 184, 132));
        jLPaciente.setForeground(Color.WHITE);
    }//GEN-LAST:event_jpPacienteMouseEntered

    private void jpPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPacienteMouseClicked
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        reinicializarBotones("paciente");
        clickVistaPacientes = true;
        PacienteVista pv = new PacienteVista();
        agregarFondoVentana(pv);
    }//GEN-LAST:event_jpPacienteMouseClicked

    private void jpDietaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDietaMouseExited
        if (!clickVistaDieta) {
            jpDieta.setBackground(new Color(195, 255, 184));
            jLDieta.setForeground(new Color(0, 54, 3));
        }
    }//GEN-LAST:event_jpDietaMouseExited

    private void jpDietaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDietaMouseEntered
        jpDieta.setBackground(new Color(140, 184, 132));
        jLDieta.setForeground(Color.WHITE);
    }//GEN-LAST:event_jpDietaMouseEntered

    private void jpDietaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDietaMouseClicked
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        reinicializarBotones("dieta");
        clickVistaDieta = true;
        DietaVista dv = new DietaVista();
        agregarFondoVentana(dv);
    }//GEN-LAST:event_jpDietaMouseClicked

    private void jpInformesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpInformesMouseClicked
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        reinicializarBotones("informes");
        clickVistaInformes = true;
        InformesVista iv = new InformesVista();
        agregarFondoVentana(iv);
    }//GEN-LAST:event_jpInformesMouseClicked

    private void jpInformesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpInformesMouseEntered
        jpInformes.setBackground(new Color(140, 184, 132));
        jLInformes.setForeground(Color.WHITE);
    }//GEN-LAST:event_jpInformesMouseEntered

    private void jpInformesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpInformesMouseExited
        if (!clickVistaInformes) {
            jpInformes.setBackground(new Color(195, 255, 184));
            jLInformes.setForeground(new Color(0, 54, 3));
        }
    }//GEN-LAST:event_jpInformesMouseExited
    public static MainMenu getMainMenu() {
        if (main == null) {
            main = new MainMenu();
        }
        return main;
    }

    public void agregarVista(JInternalFrame cmp) {
        centrarFrame(cmp);
        cmp.setVisible(true);
        jdpEscritorio.add(cmp);
        jdpEscritorio.moveToFront(cmp);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                getMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLComida;
    private javax.swing.JLabel jLDieta;
    private javax.swing.JLabel jLInformes;
    private javax.swing.JLabel jLPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JPanel jpComida;
    private javax.swing.JPanel jpDieta;
    private javax.swing.JPanel jpInformes;
    private javax.swing.JPanel jpPaciente;
    // End of variables declaration//GEN-END:variables

    private void agregarFondoVentana(JInternalFrame fv) {
        fv.setVisible(true);
        jdpEscritorio.add(fv);
        jdpEscritorio.add(jlFondo);
        jdpEscritorio.moveToFront(jlFondo);
        jdpEscritorio.moveToFront(fv);
    }

    private void centrarFrame(JInternalFrame form) {
        Dimension desktopSize = jdpEscritorio.getSize();
        int x = (desktopSize.width - form.getWidth()) / 2;
        int y = (desktopSize.height - form.getHeight()) / 2;
        form.setLocation(x, y);
    }

    public void removerVista(Component fv) {
        fv.setVisible(false);
        jdpEscritorio.remove(fv);
    }

    public void reinicializarBotones(String opc) {
        switch (opc) {
            case "paciente":
                jpComida.setBackground(new Color(195, 255, 184));
                jLComida.setForeground(new Color(0, 54, 3));
                jpDieta.setBackground(new Color(195, 255, 184));
                jLDieta.setForeground(new Color(0, 54, 3));
                jpInformes.setBackground(new Color(195, 255, 184));
                jLInformes.setForeground(new Color(0, 54, 3));
                break;
            case "comida":
                jpPaciente.setBackground(new Color(195, 255, 184));
                jLPaciente.setForeground(new Color(0, 54, 3));
                jpDieta.setBackground(new Color(195, 255, 184));
                jLDieta.setForeground(new Color(0, 54, 3));
                jpInformes.setBackground(new Color(195, 255, 184));
                jLInformes.setForeground(new Color(0, 54, 3));
                break;
            case "dieta":
                jpPaciente.setBackground(new Color(195, 255, 184));
                jLPaciente.setForeground(new Color(0, 54, 3));
                jpComida.setBackground(new Color(195, 255, 184));
                jLComida.setForeground(new Color(0, 54, 3));
                jpInformes.setBackground(new Color(195, 255, 184));
                jLInformes.setForeground(new Color(0, 54, 3));
                break;
            case "informes":
                jpPaciente.setBackground(new Color(195, 255, 184));
                jLPaciente.setForeground(new Color(0, 54, 3));
                jpComida.setBackground(new Color(195, 255, 184));
                jLComida.setForeground(new Color(0, 54, 3));
                jpDieta.setBackground(new Color(195, 255, 184));
                jLDieta.setForeground(new Color(0, 54, 3));
                break;
        }
        clickVistaPacientes = false;
        clickVistaComida = false;
        clickVistaDieta = false;
        clickVistaInformes = false;
    }

    public void reinicializarBotonesDesdeVistas() {

        clickVistaPacientes = false;
        clickVistaComida = false;
        clickVistaDieta = false;
        clickVistaInformes = false;

        jpPaciente.setBackground(new Color(195, 255, 184));
        jLPaciente.setForeground(new Color(0, 54, 3));
        jpComida.setBackground(new Color(195, 255, 184));
        jLComida.setForeground(new Color(0, 54, 3));
        jpDieta.setBackground(new Color(195, 255, 184));
        jLDieta.setForeground(new Color(0, 54, 3));
        jpInformes.setBackground(new Color(195, 255, 184));
        jLInformes.setForeground(new Color(0, 54, 3));
    }
}
